Completed express-get-json exercise.
rachel-lyy/m2-0323-code-solutions pull request #28
Opened 2023-05-10 04:41 UTC by rachel-lyy

![express-get-json](https://github.com/rachel-lyy/m2-0323-code-solutions/assets/18158834/d7eaa3bd-1ba9-4208-a5d3-318d4d94250d)

2023-05-10 15:43 UTC, TimelikeClosure requested changes

2023-05-10 15:43 UTC, TimelikeClosure commented on express-get-json/server.js
> +});
@rachel-lyy Please make sure you're sending exactly one response to each request.

---

![image](https://github.com/rachel-lyy/m2-0323-code-solutions/assets/16143771/d8dd2b61-5d42-432a-85e4-c0980ebf2d70)

2023-05-11 19:07 UTC, rachel-lyy commented
<img width="1621" alt="express-get-json-4" src="https://github.com/rachel-lyy/m2-0323-code-solutions/assets/18158834/0b2f022b-2eb0-4634-aee2-de85da3b4db1">

2023-05-12 02:17 UTC, TimelikeClosure approved these changes

2023-05-12 02:27 UTC, merged