Es6 classes
rachel-lyy/m2-0323-code-solutions pull request #6
Opened 2023-03-24 03:50 UTC by rachel-lyy

![es6-classes](https://user-images.githubusercontent.com/18158834/227419971-8a5f6852-0d8e-498d-b4cf-5036410803e2.png)

2023-03-24 04:09 UTC, scrumptiousdev requested changes

2023-03-24 04:09 UTC, scrumptiousdev commented on es6-classes/shape.js
> +  constructor(area, circumference, width) {
Per instruction:
Write its constructor to take the **square's width as a parameter** (and nothing else)

2023-03-24 04:09 UTC, scrumptiousdev commented on es6-classes/circle.js
> +  constructor(area, width, circumference, radius) {
Per instruction:
Write its constructor to take the **circle's radius as a parameter** (and nothing else)

2023-03-24 04:09 UTC, scrumptiousdev commented on es6-classes/shape.js
> +class Square extends Shape {
Also, let's move Square over to square.js

2023-03-26 20:12 UTC, rachel-lyy commented
Square
<img width="370" alt="es6-classes-square" src="https://user-images.githubusercontent.com/18158834/227801951-21a0338c-858d-451c-84df-94180ee81ef0.png">

Circle
<img width="362" alt="es6-classes-circle" src="https://user-images.githubusercontent.com/18158834/227801959-8ade70c9-26b5-40fd-b58d-0c177e0ca417.png">

2023-03-27 05:15 UTC, scrumptiousdev approved these changes
Approved! :)

2023-03-27 17:40 UTC, merged